### ISSUE TITLE
Create a test to check validity of PMID's and DOI's

### ISSUE THREAD

**Issue by gsarma** [openworm/ChannelWorm#131] opened 2015-07-26 16:35 UTC
For data entered via the curation interface.  Should be nearly identical to what we did for PyOpenWorm.  See, for example:
https://github.com/openworm/PyOpenWorm/issues/158
https://github.com/openworm/PyOpenWorm/issues/159

**Comment by travs** [comment] 2015-08-18 21:22
Duplicate of #151 and #152

**Closed by travs** 2015-08-18 21:22 UTC
Labels: testing
